image:
  name: quay.io/fenicsproject_dev/dolfin:py3-master
  entrypoint: ["/sbin/my_init","--quiet","--","/sbin/setuser","fenics"]
  
before_script:
  - source $FENICS_HOME/fenics.env.conf
  - export DIJITSO_CACHE_DIR=$CI_PROJECT_DIR/.dijitso
  - sudo apt-get -qq remove python3-pytest
  - sudo -H pip3 -q install pytest pytest-flake8 pytest-html pytest-instafail pytest-xdist
  - python3 setup.py -q install --user
  
stages:
  - build
  - test
  
build:
  stage: build
  script:
    - python3 -c "import multiphenics"
  artifacts:
    paths:
      - jitfailure*
    when: on_failure
    
flake8:
  stage: test
  script:
    - pytest --flake8 -m flake8 -n auto -vv --html=pytest_flake8.html --self-contained-html
  artifacts:
    paths:
      - pytest_flake8.html
    when: on_failure
    
tutorials_serial:
  stage: test
  script:
    - pytest -n auto -vv --html=pytest_tutorials_serial.html --self-contained-html tutorials
  artifacts:
    paths:
      - pytest_tutorials_serial.html
    when: on_failure
    
tests_serial:
  stage: test
  script:
    - pytest -n auto -vv --html=pytest_tests_serial.html --self-contained-html tests
  artifacts:
    paths:
      - pytest_tests_serial.html
    when: on_failure
    
.tutorials_parallel:
  stage: test
  script:
    - mpirun -n 2 pytest -vv --html=pytest_tutorials_parallel.html --self-contained-html tutorials
  artifacts:
    paths:
      - pytest_tutorials_parallel.html
    when: on_failure
    
.tests_parallel:
  stage: test
  script:
    - mpirun -n 2 pytest -vv --html=pytest_tests_parallel.html --self-contained-html tests
  artifacts:
    paths:
      - pytest_tests_parallel.html
    when: on_failure
